ALTER TABLE T_MAEM_FACTOR_DATA
ADD (
    FEC_REGISTRO DATE,
    USU_REGISRO VARCHAR2(50),
    IP_REGISTRO VARCHAR2(20),
    FEC_MODIFICA DATE,
    USU_MODIFICA VARCHAR2(50),
    IP_MODIFICA VARCHAR2(20)
);


CREATE TABLE T_MAEM_MRV_LG_FACTOR_DATA(
    ID_LG_FACTOR NUMERIC NOT NULL,
    FECHA_LOG DATE DEFAULT SYSDATE,
    ACCION VARCHAR2(1),
    ID_FACTOR NUMBER,
    ID_DETALE NUMBER,
    ID_PARAMETRO VARCHAR2(50),
    VALOR VARCHAR2(50),
    FACTOR NUMBER(18,4),
    FLG_ESTADO VARCHAR2(1),
    DETALLE VARCHAR2(150),
    USUARIO VARCHAR2(20),
    IP VARCHAR2(20),
    CONSTRAINT PK_LG_FACTOR_DATA PRIMARY KEY(ID_LG_FACTOR)
);


create sequence SQ_MAEM_LG_FACTOR_DATA
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1;


CREATE TABLE T_MAEM_MRV_BLOCKCHAIN(
    ID_INICIATIVA NUMBER,
    ID_CORRELATIVO INTEGER,
    ID_ETAPA INTEGER,
    VALOR HASH,
    FEC_REGISTRO DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BLOCKCHAIN PRIMARY KEY(ID_INICIATIVA, ID_CORRELATIVO)
);


