ALTER TABLE T_GEND_INDICADOR
ADD ADJUNTO_BASE VARCHAR2(100);

ALTER TABLE T_GEND_INICIATIVA_SUSTENTA
ADD ADJUNTO_BASE VARCHAR2(100);

ALTER TABLE T_GENM_NOTIFICACION
ADD ID_USUARIO_REMITENTE INTEGER;
