--------------------------------------------------------
-- Permisos para paquetes
-- Archivo creado  - viernes-Marzo-20-2020 
-- Se ejecuta desde el System  
--------------------------------------------------------

GRANT EXECUTE ON MRVMM.PKG_MRV_ADMIN_SISTEMA TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_BLOCKCHAIN TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_DETALLE_INDICADORES TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_DIRECCIONAMIENTO TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_INICIATIVA_MITIGACION TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_MANTENIMIENTO TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_NOTIFICACION TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_PARAMETROS TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_REPORTES TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_VARIABLES TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.SHA256 TO MRVMM_CON;
