--------------------------------------------------------
-- Permisos para paquetes
-- Archivo creado  - jueves-enero-31-2020   
--------------------------------------------------------

GRANT EXECUTE ON MRVMM.PKG_MRV_ADMIN_SISTEMA TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_CALCULO TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_DETALLE_INDICADORES TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_INICIATIVA_MITIGACION TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_MANTENIMIENTO TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_NOTIFICACION TO MRVMM_CON;
GRANT EXECUTE ON MRVMM.PKG_MRV_REPORTES TO MRVMM_CON;