--------------------------------------------------------
-- Archivo creado  - martes-enero-07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SQ_GEND_ENFOQUE_FORMULA
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GEND_ENFOQUE_FORMULA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GEND_FORMULA_VARIABLE
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GEND_FORMULA_VARIABLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GEND_INDICADOR_ENFOQUE
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GEND_INDICADOR_ENFOQUE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GEND_INICIATIVA_ENERG
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GEND_INICIATIVA_ENERG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GEND_INICIATIVA_GEI
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GEND_INICIATIVA_GEI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GEND_INICIATIVA_UBICACION
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GEND_INICIATIVA_UBICACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GENM_ENFOQUE
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GENM_ENFOQUE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GENM_ENFOQUE_FORMULA
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GENM_ENFOQUE_FORMULA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GENM_INICIATIVA
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GENM_INICIATIVA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GENM_INSTITUCION
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GENM_INSTITUCION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_GENM_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "USERMRV"."SQ_GENM_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Table T_GEND_ENFOQUE_FORMULA
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_ENFOQUE_FORMULA" 
   (	"ID_ENFOQUE_FORMULA" NUMBER(*,0), 
	"ID_ENFOQUE" NUMBER(*,0), 
	"ID_FORMULA" NUMBER(*,0), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GEND_FORMULA_VARIABLE
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_FORMULA_VARIABLE" 
   (	"ID_FORMULA_VARIABLE" NUMBER(*,0), 
	"ID_FORMULA" NUMBER(*,0), 
	"ID_VARIABLE" NUMBER(*,0), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GEND_INDICADOR
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_INDICADOR" 
   (	"ID_INDICADOR" NUMBER(*,0), 
	"ID_INICIATIVA" NUMBER(*,0), 
	"ID_MEDMIT" NUMBER(*,0), 
	"ANNO" NUMBER(*,4), 
	"SUBTOTAL" NUMBER(18,4), 
	"ID_ADJUNTO" NUMBER(18,4), 
	"FLG_ESTADO" NUMBER(*,0), 
	"FECHA_REGISTRO" DATE, 
	"ID_ETAPA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GEND_INDICADOR_ENFOQUE
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_INDICADOR_ENFOQUE" 
   (	"ID_INDICADOR_ENFOQUE" NUMBER(*,0), 
	"ID_INDICADOR" NUMBER(*,0), 
	"ID_ENFOQUE" NUMBER(*,0), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GEND_INICIATIVA_COMP
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_INICIATIVA_COMP" 
   (	"ID_INICIATIVA_COMP" NUMBER(*,0), 
	"ID_INICIATIVA" NUMBER(*,0), 
	"ID_LISTA" NUMBER(*,0), 
	"VALOR" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GEND_INICIATIVA_ENERG
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_INICIATIVA_ENERG" 
   (	"ID_INICIATIVA_ENERG" NUMBER(*,0), 
	"ID_INICIATIVA" NUMBER(*,0), 
	"ID_ENERG" NUMBER(*,0), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GEND_INICIATIVA_GEI
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_INICIATIVA_GEI" 
   (	"ID_INICIATIVA_GEI" NUMBER(*,0), 
	"ID_INICIATIVA" NUMBER(*,0), 
	"ID_GEI" NUMBER(*,0), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GEND_INICIATIVA_UBICACION
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_INICIATIVA_UBICACION" 
   (	"ID_INICIATIVA_UBICACION" NUMBER(*,0), 
	"ID_INICIATIVA" NUMBER(*,0), 
	"ID_UBICACION" NUMBER(*,0), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GEND_INI_TIPDOCAVAL
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_INI_TIPDOCAVAL" 
   (	"ID_GEND_INDICOMPU_TIPDOCAVAL" NUMBER(*,0), 
	"ID_TIPDOCAVAL" NUMBER(*,0), 
	"ID_INI_TIPDOCAVAL" CHAR(18 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GEND_SEGUIMIENTO
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GEND_SEGUIMIENTO" 
   (	"ID_SEGUIMIENTO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"FECHAREGISTRO" DATE, 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ID_ETAPA" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_AYUDA
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_AYUDA" 
   (	"ID_AYUDA" NUMBER(*,0), 
	"DES_VIS_ES" VARCHAR2(500 BYTE), 
	"DES_TEC_ES" VARCHAR2(500 BYTE), 
	"DES_VIS_EN" VARCHAR2(500 BYTE), 
	"DES_TEC_EN" VARCHAR2(500 BYTE), 
	"ID_MAEPAGSEC" NUMBER(*,0), 
	"CODIGOAYUDA" VARCHAR2(5 BYTE), 
	"ID_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_BLOCKCHAIN
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_BLOCKCHAIN" 
   (	"ID_BLOCKCHAIN" NUMBER(*,0), 
	"ID_INICIATIVA" NUMBER(*,0), 
	"HASH" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_ENFOQUE
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_ENFOQUE" 
   (	"ID_ENFOQUE" NUMBER(*,0), 
	"ID_MEDMIT" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_ESCENARIO
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_ESCENARIO" 
   (	"ID_ESCENARIO" NUMBER(*,0), 
	"ID_MEDMIT" NUMBER(*,0), 
	"ANNO" NUMBER(*,0), 
	"BAU_EMISION" NUMBER(10,2), 
	"MIT_EMISION" NUMBER(10,2), 
	"REDUCCION" NUMBER(10,2), 
	"VALOR_SOFTWARE" NUMBER(10,2), 
	"EXPOST" NUMBER(10,2), 
	"META_ANUAL" NUMBER(10,2), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_FACTOR
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_FACTOR" 
   (	"ID_FACTOR" NUMBER(*,0), 
	"ID_FORMULA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"SIGLA" VARCHAR2(50 BYTE), 
	"FUNCION" NUMBER(18,4), 
	"VALOR" NUMBER(18,4)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_FORMULA
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_FORMULA" 
   (	"ID_FORMULA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_INICIATIVA
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_INICIATIVA" 
   (	"ID_INICIATIVA" NUMBER(*,0), 
	"ID_MEDMIT" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE_INICIATIVA" VARCHAR2(2000 BYTE), 
	"DESC_INICIATIVA" VARCHAR2(2000 BYTE), 
	"ID_ESTADO" NUMBER(*,0), 
	"PRIVACIDAD_INICIATIVA" CHAR(1 BYTE), 
	"INVERSION_INICIATIVA" NUMBER(10,2), 
	"ID_MONEDA" NUMBER(*,0), 
	"FECHA_CREA_INICIATIVA" DATE, 
	"FECHA_IMPLE_INICIATIVA" DATE, 
	"ID_ETAPA" NUMBER(*,0), 
	"USUARIO_REGISTRO" NUMBER(*,0), 
	"FECHA_REGISTRO" DATE, 
	"IP_REGISTRO" VARCHAR2(50 BYTE), 
	"USUARIO_MODIFICA" NUMBER(*,0), 
	"FECHA_MODIFICA" DATE, 
	"IP_MODIFICA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_INSTITUCION
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_INSTITUCION" 
   (	"ID_INSTITUCION" NUMBER(*,0), 
	"ID_SECTOR_INSTITUCION" NUMBER(*,0), 
	"RUC_INSTITUCION" VARCHAR2(20 BYTE), 
	"NOMBRE_INSTITUCION" VARCHAR2(200 BYTE), 
	"DIRECCION_INSTITUCION" VARCHAR2(100 BYTE), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_USUARIO
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_USUARIO" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRES_USUARIO" CHAR(20 BYTE), 
	"APELLIDOS_USUARIO" VARCHAR2(30 BYTE), 
	"ID_INSTITUCION" NUMBER(*,0), 
	"PASSWORD_USUARIO" VARCHAR2(100 BYTE), 
	"EMAIL_USUARIO" VARCHAR2(40 BYTE), 
	"ID_ESTADO_USUARIO" NUMBER(*,0), 
	"TELEFONO_USUARIO" VARCHAR2(20 BYTE), 
	"CELULAR_USUARIO" VARCHAR2(20 BYTE), 
	"FLG_ESTADO" CHAR(1 BYTE), 
	"ID_TERMINOS" NUMBER, 
	"FLG_TERMINOS" CHAR(1 BYTE), 
	"ANEXO_USUARIO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENM_VARIABLE
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_GENM_VARIABLE" 
   (	"ID_VARIABLE" NUMBER(*,0), 
	"ID_FORMULA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"SIGLA" VARCHAR2(50 BYTE), 
	"VALOR" NUMBER(18,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_ENERG
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_ENERG" 
   (	"ID_ENERG" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_ESTADO
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_ESTADO" 
   (	"ID_ESTADO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_ESTADO_USUARIO
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_ESTADO_USUARIO" 
   (	"ID_ESTADO_USUARIO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_ETAPA
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_ETAPA" 
   (	"ID_ETAPA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_F_BAU
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_F_BAU" 
   (	"ID_F_BAU" NUMBER(*,0), 
	"ID_TIPO_VEHICULO" NUMBER(*,0), 
	"ID_TIPO_COMBUSTIBLE" NUMBER(*,0), 
	"ANNO" NUMBER(*,0), 
	"FACTOR" NUMBER(18,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_F_MIT
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_F_MIT" 
   (	"ID_F_MIT" NUMBER(*,0), 
	"ID_TIPO_VEHICULO" NUMBER(*,0), 
	"ID_TIPO_FUENTE" NUMBER(*,0), 
	"ANNO" NUMBER(*,0), 
	"FACTOR" NUMBER(18,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_F_PER
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_F_PER" 
   (	"ID_F_PER" NUMBER(*,0), 
	"ANNO" NUMBER(*,0), 
	"FACTOR" NUMBER(18,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_GEI
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_GEI" 
   (	"ID_GEI" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_LISTA
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_LISTA" 
   (	"ID_LISTA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_MEDMIT
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_MEDMIT" 
   (	"ID_MEDMIT" NUMBER(*,0), 
	"NUMERO_MEDMIT" VARCHAR2(50 BYTE), 
	"NOMBRE_MEDMIT" VARCHAR2(200 BYTE), 
	"DESCRIPCION_MEDMIT" VARCHAR2(2000 BYTE), 
	"ID_NAMA" NUMBER(*,0), 
	"OBJETIVO_MEDMIT" VARCHAR2(2000 BYTE), 
	"IPSC_MEDMIT" VARCHAR2(50 BYTE), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_MONEDA
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_MONEDA" 
   (	"ID_MONEDA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_NAMA
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_NAMA" 
   (	"ID_NAMA" NUMBER(*,0), 
	"DESCRIPCION_NAMA" VARCHAR2(100 BYTE), 
	"FLG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_OPCION
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_OPCION" 
   (	"ID_OPCION" NUMBER, 
	"DES_OPCION" VARCHAR2(200 BYTE), 
	"FLG_ESTADO" CHAR(1 BYTE), 
	"DES_URL" VARCHAR2(128 BYTE), 
	"DES_URLIMAGEN" VARCHAR2(128 BYTE), 
	"DES_URLLABEL" VARCHAR2(128 BYTE), 
	"DES_FUNCION_INI" VARCHAR2(100 BYTE), 
	"NUM_ORDEN" NUMBER(4,0), 
	"NUM_NIVEL" NUMBER(4,0), 
	"ID_OPCION_PADRE" NUMBER, 
	"ID_TIPO_OPCION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_OPCION_ROL
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_OPCION_ROL" 
   (	"ID_OPCION" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0), 
	"FLG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_PAGINA
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_PAGINA" 
   (	"ID_PAGINA" NUMBER(*,0), 
	"CODIGO_PAGINA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_PLAZO
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_PLAZO" 
   (	"ID_PLAZO" NUMBER(*,0), 
	"DIAS_PLAZO" NUMBER(*,0), 
	"ID_ETAPA" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_ROL
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_ROL" 
   (	"ID_ROL" NUMBER(*,0), 
	"DESCRIPCION_ROL" VARCHAR2(50 BYTE), 
	"FLG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_SECTOR_INST
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_SECTOR_INST" 
   (	"ID_SECTOR_INST" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"FLAG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_TERMINOS
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_TERMINOS" 
   (	"ID_TERMINOS" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0), 
	"CONDICIONES_TERMINOS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_TIPO_COMBUSTIBLE
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_TIPO_COMBUSTIBLE" 
   (	"ID_TIPO_COMBUSTIBLE" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_TIPO_FUENTE
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_TIPO_FUENTE" 
   (	"ID_TIPO_FUENTE" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_TIPO_OPCION
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_TIPO_OPCION" 
   (	"ID_TIPO_OPCION" NUMBER, 
	"DES_TIPO_OPCION" VARCHAR2(60 BYTE), 
	"SIGLA" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_TIPO_VEHICULO
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_TIPO_VEHICULO" 
   (	"ID_TIPO_VEHICULO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_UBICACION
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_UBICACION" 
   (	"ID_UBICACION" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"FLG_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_MAE_USUARIO_ROL
--------------------------------------------------------

  CREATE TABLE "USERMRV"."T_MAE_USUARIO_ROL" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0), 
	"FLG_ESTADO" CHAR(1 BYTE), 
	"DES_COMENTARIO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GEND_ENFOQUE_FORMULA_PK
--------------------------------------------------------

  CREATE INDEX "USERMRV"."GEND_ENFOQUE_FORMULA_PK" ON "USERMRV"."T_GEND_ENFOQUE_FORMULA" ("ID_ENFOQUE_FORMULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GEND_FORMULA_VARIABLE_PK
--------------------------------------------------------

  CREATE INDEX "USERMRV"."GEND_FORMULA_VARIABLE_PK" ON "USERMRV"."T_GEND_FORMULA_VARIABLE" ("ID_FORMULA_VARIABLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GEND_INDICADOR_ENFOQUE_PK
--------------------------------------------------------

  CREATE INDEX "USERMRV"."GEND_INDICADOR_ENFOQUE_PK" ON "USERMRV"."T_GEND_INDICADOR_ENFOQUE" ("ID_INDICADOR_ENFOQUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GENM_FACTOR_PK
--------------------------------------------------------

  CREATE INDEX "USERMRV"."GENM_FACTOR_PK" ON "USERMRV"."T_GENM_FACTOR" ("ID_FACTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GENM_FORMULA_PK
--------------------------------------------------------

  CREATE INDEX "USERMRV"."GENM_FORMULA_PK" ON "USERMRV"."T_GENM_FORMULA" ("ID_FORMULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GENM_VARIABLE_PK
--------------------------------------------------------

  CREATE INDEX "USERMRV"."GENM_VARIABLE_PK" ON "USERMRV"."T_GENM_VARIABLE" ("ID_VARIABLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GEND_INICIATIVA_ENERG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GEND_INICIATIVA_ENERG_PK" ON "USERMRV"."T_GEND_INICIATIVA_ENERG" ("ID_INICIATIVA_ENERG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GEND_INICIATIVA_GEI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GEND_INICIATIVA_GEI_PK" ON "USERMRV"."T_GEND_INICIATIVA_GEI" ("ID_INICIATIVA_GEI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GEND_INICIATIVA_UBICACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GEND_INICIATIVA_UBICACION_PK" ON "USERMRV"."T_GEND_INICIATIVA_UBICACION" ("ID_INICIATIVA_UBICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GEND_SEGUIMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GEND_SEGUIMIENTO_PK" ON "USERMRV"."T_GEND_SEGUIMIENTO" ("ID_SEGUIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GENM_AYUDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GENM_AYUDA_PK" ON "USERMRV"."T_GENM_AYUDA" ("ID_AYUDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GENM_BLOCKCHAIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GENM_BLOCKCHAIN_PK" ON "USERMRV"."T_GENM_BLOCKCHAIN" ("ID_BLOCKCHAIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GENM_ESCENARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GENM_ESCENARIO_PK" ON "USERMRV"."T_GENM_ESCENARIO" ("ID_ESCENARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GENM_INICIATIVA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GENM_INICIATIVA_PK" ON "USERMRV"."T_GENM_INICIATIVA" ("ID_INICIATIVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GENM_INSTITUCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GENM_INSTITUCION_PK" ON "USERMRV"."T_GENM_INSTITUCION" ("ID_INSTITUCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GENM_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_GENM_USUARIO_PK" ON "USERMRV"."T_GENM_USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_ENERG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_ENERG_PK" ON "USERMRV"."T_MAE_ENERG" ("ID_ENERG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_ESTADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_ESTADO_PK" ON "USERMRV"."T_MAE_ESTADO" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_ESTADO_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_ESTADO_USUARIO_PK" ON "USERMRV"."T_MAE_ESTADO_USUARIO" ("ID_ESTADO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_ETAPA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_ETAPA_PK" ON "USERMRV"."T_MAE_ETAPA" ("ID_ETAPA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_GEI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_GEI_PK" ON "USERMRV"."T_MAE_GEI" ("ID_GEI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_LISTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_LISTA_PK" ON "USERMRV"."T_MAE_LISTA" ("ID_LISTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_MEDMIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_MEDMIT_PK" ON "USERMRV"."T_MAE_MEDMIT" ("ID_MEDMIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_MONEDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_MONEDA_PK" ON "USERMRV"."T_MAE_MONEDA" ("ID_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_NAMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_NAMA_PK" ON "USERMRV"."T_MAE_NAMA" ("ID_NAMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_OPCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_OPCION_PK" ON "USERMRV"."T_MAE_OPCION" ("ID_OPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_PAGINA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_PAGINA_PK" ON "USERMRV"."T_MAE_PAGINA" ("ID_PAGINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_PLAZO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_PLAZO_PK" ON "USERMRV"."T_MAE_PLAZO" ("ID_PLAZO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_ROL_PK" ON "USERMRV"."T_MAE_ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_SECTOR_INST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_SECTOR_INST_PK" ON "USERMRV"."T_MAE_SECTOR_INST" ("ID_SECTOR_INST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_TERMINOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_TERMINOS_PK" ON "USERMRV"."T_MAE_TERMINOS" ("ID_TERMINOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_MAE_UBICACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERMRV"."T_MAE_UBICACION_PK" ON "USERMRV"."T_MAE_UBICACION" ("ID_UBICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TR_GEND_ENFOQUE_FORMULA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USERMRV"."TR_GEND_ENFOQUE_FORMULA" 
BEFORE INSERT ON T_GEND_ENFOQUE_FORMULA
FOR EACH ROW
BEGIN
SELECT SQ_GEND_ENFOQUE_FORMULA.NEXTVAL INTO:
NEW.ID_ENFOQUE_FORMULA FROM DUAL;
END;
/
ALTER TRIGGER "USERMRV"."TR_GEND_ENFOQUE_FORMULA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_GEND_FORMULA_VARIABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USERMRV"."TR_GEND_FORMULA_VARIABLE" 
BEFORE INSERT ON T_GEND_FORMULA_VARIABLE
FOR EACH ROW
BEGIN
SELECT SQ_GEND_FORMULA_VARIABLE.NEXTVAL INTO:
NEW.ID_FORMULA_VARIABLE FROM DUAL;
END; 
/
ALTER TRIGGER "USERMRV"."TR_GEND_FORMULA_VARIABLE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_GEND_INDICADOR_ENFOQUE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USERMRV"."TR_GEND_INDICADOR_ENFOQUE" 
BEFORE INSERT ON T_GEND_INDICADOR_ENFOQUE
FOR EACH ROW
BEGIN
SELECT SQ_GEND_INDICADOR_ENFOQUE.NEXTVAL INTO:
NEW.ID_INDICADOR_ENFOQUE FROM DUAL;
END;
/
ALTER TRIGGER "USERMRV"."TR_GEND_INDICADOR_ENFOQUE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_GEND_INICIATIVA_ENERG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USERMRV"."TR_GEND_INICIATIVA_ENERG" 
BEFORE INSERT ON T_GEND_INICIATIVA_ENERG
FOR EACH ROW
BEGIN
SELECT SQ_GEND_INICIATIVA_ENERG.NEXTVAL INTO:
NEW.ID_INICIATIVA_ENERG FROM DUAL;
END;
/
ALTER TRIGGER "USERMRV"."TR_GEND_INICIATIVA_ENERG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_GEND_INICIATIVA_GEI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USERMRV"."TR_GEND_INICIATIVA_GEI" 
BEFORE INSERT ON T_GEND_INICIATIVA_GEI
FOR EACH ROW
BEGIN
SELECT SQ_GEND_INICIATIVA_GEI.NEXTVAL INTO:
NEW.ID_INICIATIVA_GEI FROM DUAL;
END;
/
ALTER TRIGGER "USERMRV"."TR_GEND_INICIATIVA_GEI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_GEND_INICIATIVA_UBICACION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USERMRV"."TR_GEND_INICIATIVA_UBICACION" 
BEFORE INSERT ON T_GEND_INICIATIVA_UBICACION
FOR EACH ROW
BEGIN
SELECT SQ_GEND_INICIATIVA_UBICACION.NEXTVAL INTO:
NEW.ID_INICIATIVA_UBICACION FROM DUAL;
END;
/
ALTER TRIGGER "USERMRV"."TR_GEND_INICIATIVA_UBICACION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_GENM_INICIATIVA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USERMRV"."TR_GENM_INICIATIVA" 
BEFORE INSERT ON T_GENM_INICIATIVA
FOR EACH ROW
BEGIN
SELECT SQ_GENM_INICIATIVA.NEXTVAL INTO:
NEW.id_iniciativa FROM DUAL;
END;
/
ALTER TRIGGER "USERMRV"."TR_GENM_INICIATIVA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_GENM_INSTITUCION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USERMRV"."TR_GENM_INSTITUCION" 
BEFORE INSERT ON T_GENM_INSTITUCION
FOR EACH ROW
BEGIN
SELECT SQ_GENM_INSTITUCION.NEXTVAL INTO:
NEW.ID_INSTITUCION FROM DUAL;
END;
/
ALTER TRIGGER "USERMRV"."TR_GENM_INSTITUCION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_GENM_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USERMRV"."TR_GENM_USUARIO" 
BEFORE INSERT ON T_GENM_USUARIO
FOR EACH ROW
BEGIN
SELECT SQ_GENM_USUARIO.NEXTVAL INTO:
NEW.id_usuario FROM DUAL;
END;
/
ALTER TRIGGER "USERMRV"."TR_GENM_USUARIO" ENABLE;
--------------------------------------------------------
--  Constraints for Table T_GEND_INICIATIVA_ENERG
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GEND_INICIATIVA_ENERG" ADD CONSTRAINT "T_GEND_INICIATIVA_ENERG_PK" PRIMARY KEY ("ID_INICIATIVA_ENERG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERMRV"."T_GEND_INICIATIVA_ENERG" MODIFY ("ID_ENERG" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GEND_INICIATIVA_ENERG" MODIFY ("ID_INICIATIVA" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GEND_INICIATIVA_ENERG" MODIFY ("ID_INICIATIVA_ENERG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GEND_INICIATIVA_GEI
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GEND_INICIATIVA_GEI" ADD CONSTRAINT "T_GEND_INICIATIVA_GEI_PK" PRIMARY KEY ("ID_INICIATIVA_GEI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_GEND_INICIATIVA_UBICACION
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GEND_INICIATIVA_UBICACION" ADD CONSTRAINT "T_GEND_INICIATIVA_UBICACION_PK" PRIMARY KEY ("ID_INICIATIVA_UBICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERMRV"."T_GEND_INICIATIVA_UBICACION" MODIFY ("ID_UBICACION" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GEND_INICIATIVA_UBICACION" MODIFY ("ID_INICIATIVA" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GEND_INICIATIVA_UBICACION" MODIFY ("ID_INICIATIVA_UBICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GEND_INI_TIPDOCAVAL
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GEND_INI_TIPDOCAVAL" MODIFY ("ID_INI_TIPDOCAVAL" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GEND_INI_TIPDOCAVAL" MODIFY ("ID_TIPDOCAVAL" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GEND_INI_TIPDOCAVAL" MODIFY ("ID_GEND_INDICOMPU_TIPDOCAVAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GEND_SEGUIMIENTO
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GEND_SEGUIMIENTO" ADD CONSTRAINT "T_GEND_SEGUIMIENTO_PK" PRIMARY KEY ("ID_SEGUIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERMRV"."T_GEND_SEGUIMIENTO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GEND_SEGUIMIENTO" MODIFY ("ID_SEGUIMIENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GENM_AYUDA
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GENM_AYUDA" ADD CONSTRAINT "T_GENM_AYUDA_PK" PRIMARY KEY ("ID_AYUDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERMRV"."T_GENM_AYUDA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GENM_AYUDA" MODIFY ("ID_MAEPAGSEC" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GENM_AYUDA" MODIFY ("ID_AYUDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GENM_BLOCKCHAIN
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GENM_BLOCKCHAIN" ADD CONSTRAINT "T_GENM_BLOCKCHAIN_PK" PRIMARY KEY ("ID_BLOCKCHAIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_GENM_ESCENARIO
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GENM_ESCENARIO" ADD CONSTRAINT "T_GENM_ESCENARIO_PK" PRIMARY KEY ("ID_ESCENARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_GENM_INICIATIVA
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GENM_INICIATIVA" ADD CONSTRAINT "T_GENM_INICIATIVA_PK" PRIMARY KEY ("ID_INICIATIVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_GENM_INSTITUCION
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GENM_INSTITUCION" ADD CONSTRAINT "T_GENM_INSTITUCION_PK" PRIMARY KEY ("ID_INSTITUCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_GENM_USUARIO
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GENM_USUARIO" ADD CONSTRAINT "T_GENM_USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_ENERG
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_ENERG" ADD CONSTRAINT "T_MAE_ENERG_PK" PRIMARY KEY ("ID_ENERG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_ESTADO
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_ESTADO" ADD CONSTRAINT "T_MAE_ESTADO_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_ESTADO_USUARIO
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_ESTADO_USUARIO" ADD CONSTRAINT "T_MAE_ESTADO_USUARIO_PK" PRIMARY KEY ("ID_ESTADO_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_ETAPA
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_ETAPA" ADD CONSTRAINT "T_MAE_ETAPA_PK" PRIMARY KEY ("ID_ETAPA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_GEI
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_GEI" ADD CONSTRAINT "T_MAE_GEI_PK" PRIMARY KEY ("ID_GEI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_LISTA
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_LISTA" ADD CONSTRAINT "T_MAE_LISTA_PK" PRIMARY KEY ("ID_LISTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_MEDMIT
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_MEDMIT" ADD CONSTRAINT "T_MAE_MEDMIT_PK" PRIMARY KEY ("ID_MEDMIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_MONEDA
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_MONEDA" ADD CONSTRAINT "T_MAE_MONEDA_PK" PRIMARY KEY ("ID_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_NAMA
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_NAMA" MODIFY ("ID_NAMA" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_NAMA" ADD CONSTRAINT "T_MAE_NAMA_PK" PRIMARY KEY ("ID_NAMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_OPCION
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_OPCION" ADD CONSTRAINT "T_MAE_OPCION_PK" PRIMARY KEY ("ID_OPCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERMRV"."T_MAE_OPCION" MODIFY ("FLG_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_OPCION" MODIFY ("DES_OPCION" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_OPCION" MODIFY ("ID_OPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_MAE_OPCION_ROL
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_OPCION_ROL" MODIFY ("FLG_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_OPCION_ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_OPCION_ROL" MODIFY ("ID_OPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_MAE_PAGINA
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_PAGINA" ADD CONSTRAINT "T_MAE_PAGINA_PK" PRIMARY KEY ("ID_PAGINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_PLAZO
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_PLAZO" MODIFY ("ID_ETAPA" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_PLAZO" MODIFY ("ID_PLAZO" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_PLAZO" ADD CONSTRAINT "T_MAE_PLAZO_PK" PRIMARY KEY ("ID_PLAZO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_ROL
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_ROL" MODIFY ("FLG_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_ROL" ADD CONSTRAINT "T_MAE_ROL_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_SECTOR_INST
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_SECTOR_INST" ADD CONSTRAINT "T_MAE_SECTOR_INST_PK" PRIMARY KEY ("ID_SECTOR_INST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_TERMINOS
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_TERMINOS" ADD CONSTRAINT "T_MAE_TERMINOS_PK" PRIMARY KEY ("ID_TERMINOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERMRV"."T_MAE_TERMINOS" MODIFY ("CONDICIONES_TERMINOS" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_TERMINOS" MODIFY ("ID_TERMINOS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_MAE_TIPO_OPCION
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_TIPO_OPCION" MODIFY ("DES_TIPO_OPCION" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_TIPO_OPCION" MODIFY ("ID_TIPO_OPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_MAE_UBICACION
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_UBICACION" ADD CONSTRAINT "T_MAE_UBICACION_PK" PRIMARY KEY ("ID_UBICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAE_USUARIO_ROL
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_MAE_USUARIO_ROL" MODIFY ("FLG_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_USUARIO_ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_MAE_USUARIO_ROL" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_GENM_USUARIO
--------------------------------------------------------

  ALTER TABLE "USERMRV"."T_GENM_USUARIO" ADD CONSTRAINT "T_USUARIO_INSTITUCION_FK" FOREIGN KEY ("ID_INSTITUCION")
	  REFERENCES "USERMRV"."T_GENM_INSTITUCION" ("ID_INSTITUCION") ENABLE;
