CREATE TABLE "USERMRV"."T_GENM_NOTIFICACION" 
   (	"ID_NOTIFICACION" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_INICIATIVA" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ETAPA" NUMBER(*,0), 
	"ID_ESTADO" NUMBER(*,0), 
	"FECHA_REGISTRO" DATE, 
	"ID_ROL" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"FLG_VISTO" VARCHAR2(1) DEFAULT 0, 
	"FECHA_VISTO" DATE, 
	"ID_USUARIO_VISTO" NUMBER(*,0)
   ) ;
  
  CREATE INDEX "USERMRV"."GENM_NOTIFICACION_PK" ON "USERMRV"."T_GENM_NOTIFICACION" ("ID_NOTIFICACION") ;
  ALTER TABLE "USERMRV"."T_GENM_NOTIFICACION" MODIFY ("ID_INICIATIVA" NOT NULL ENABLE);
  ALTER TABLE "USERMRV"."T_GENM_NOTIFICACION" MODIFY ("ID_NOTIFICACION" NOT NULL ENABLE);